export const FORM_SCHEMAS = [
  {
    "component_id": 26,
    "msg_type": "R",
    "name": "QuoteRequest",
    "category_id": "QuotationNegotiation",
    "section_id": "PreTrade",
    "abbr_name": "QuotReq",
    "not_req_xml": false,
    "description": "In some markets it is the practice to request quotes from brokers prior to placement of an order. The quote request message is used for this purpose. This message is commonly referred to as an Request For Quote (RFQ)",
    "elaboration": "",
    "added": "FIX.4.0",
    "updated": "",
    "deprecated": "",
    "addedEP": "",
    "updatedEP": "",
    "deprecatedEP": ""
  },
  {
    "component_id": 66,
    "msg_type": "AG",
    "name": "QuoteRequestReject",
    "category_id": "QuotationNegotiation",
    "section_id": "PreTrade",
    "abbr_name": "QuotReqRej",
    "not_req_xml": false,
    "description": "The Quote Request Reject message is used to reject Quote Request messages for all quoting models.",
    "elaboration": "",
    "added": "FIX.4.3",
    "updated": "",
    "deprecated": "",
    "addedEP": "",
    "updatedEP": "",
    "deprecatedEP": ""
  },
  {
    "component_id": 69,
    "msg_type": "AJ",
    "name": "QuoteResponse",
    "category_id": "QuotationNegotiation",
    "section_id": "PreTrade",
    "abbr_name": "QuotRsp",
    "not_req_xml": false,
    "description": "The Quote Response message is used to respond to a IOI message or Quote message. It is also used to counter a Quote or end a negotiation dialog.",
    "elaboration": "",
    "added": "FIX.4.4",
    "updated": "",
    "deprecated": "",
    "addedEP": "",
    "updatedEP": "",
    "deprecatedEP": ""
  },

  {
    "component_id": 70,
    "msg_type": "AK",
    "name": "Confirmation",
    "category_id": "Confirmation",
    "section_id": "PostTrade",
    "abbr_name": "Cnfm",
    "not_req_xml": false,
    "description": "The Confirmation messages are used to provide individual trade level confirmations from the sell side to the buy side. In versions of FIX prior to version 4.4, this role was performed by the allocation message. Unlike the allocation message, the confirmation message operates at an allocation account (trade) level rather than block level, allowing for the affirmation or rejection of individual confirmations.",
    "elaboration": "",
    "added": "FIX.4.4",
    "updated": "",
    "deprecated": "",
    "addedEP": "",
    "updatedEP": "",
    "deprecatedEP": ""
  },
  {
    "component_id": 14,
    "msg_type": "D",
    "name": "NewOrderSingle",
    "category_id": "SingleGeneralOrderHandling",
    "section_id": "Trade",
    "abbr_name": "Order",
    "not_req_xml": false,
    "description": "The new order message type is used by institutions wishing to electronically submit securities and forex orders to a broker for execution.\nThe New Order message type may also be used by institutions or retail intermediaries wishing to electronically submit Collective Investment Vehicle (CIV) orders to a broker or fund manager for execution.",
    "elaboration": "",
    "added": "FIX.2.7",
    "updated": "",
    "deprecated": "",
    "addedEP": "",
    "updatedEP": "",
    "deprecatedEP": ""
  },
  {
    "component_id": 16,
    "msg_type": "F",
    "name": "OrderCancelRequest",
    "category_id": "SingleGeneralOrderHandling",
    "section_id": "Trade",
    "abbr_name": "OrdCxlReq",
    "not_req_xml": false,
    "description": "The order cancel request message requests the cancellation of all of the remaining quantity of an existing order. Note that the Order Cancel/Replace Request should be used to partially cancel (reduce) an order).",
    "elaboration": "",
    "added": "FIX.2.7",
    "updated": "",
    "deprecated": "",
    "addedEP": "",
    "updatedEP": "",
    "deprecatedEP": ""
  },
  {
    "component_id": 18,
    "msg_type": "H",
    "name": "OrderStatusRequest",
    "category_id": "SingleGeneralOrderHandling",
    "section_id": "Trade",
    "abbr_name": "OrdStatReq",
    "not_req_xml": false,
    "description": "The order status request message is used by the institution to generate an order status message back from the broker.",
    "elaboration": "",
    "added": "FIX.2.7",
    "updated": "",
    "deprecated": "",
    "addedEP": "",
    "updatedEP": "",
    "deprecatedEP": ""
  },
  {
    "component_id": 9,
    "msg_type": "8",
    "name": "ExecutionReport",
    "category_id": "SingleGeneralOrderHandling",
    "section_id": "Trade",
    "abbr_name": "ExecRpt",
    "not_req_xml": false,
    "description": "The execution report message is used to:\n1. confirm the receipt of an order\n2. confirm changes to an existing order (i.e. accept cancel and replace requests)\n3. relay order status information\n4. relay fill information on working orders\n5. relay fill information on tradeable or restricted tradeable quotes\n6. reject orders\n7. report post-trade fees calculations associated with a trade",
    "elaboration": "",
    "added": "FIX.2.7",
    "updated": "",
    "deprecated": "",
    "addedEP": "",
    "updatedEP": "",
    "deprecatedEP": ""
  }
]
